import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import PortfolioItem from '@/components/portfolio/portfolioItem'
import Background from '@/components/background/background'

import OscarDevContextProvider from '@/store/OscarDevContextProvider';
import React, { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home( {portfolioItems}:any ){

  console.log({portfolioItems});

  return (
    <>
      <OscarDevContextProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`row ${styles.main}`}>
          {portfolioItems.nodes.map( (item: any) => {
            // return(<h1 key={item.id}>{item.title}</h1>)
            return(<PortfolioItem  key={item.slug} pItem = {item}/>);
          })}
        </main>
      </OscarDevContextProvider>
    </>
  )
}

export async function getStaticProps(){
  const res = await fetch('http://oscar-dev.online/graphql', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: `
        query getPortfolioItems {
          portfolioItems {
            nodes {
              id
              slug
              title
              featuredImage {
                node {
                  altText
                  sourceUrl
                }
              }
            }
          }
        }
      `
    }),
  });

  const json = await res.json();

  return {
    props: {
      portfolioItems: json.data.portfolioItems
    }
  }
}